# CircleCi Configuration for local_pathfinding

version: 2.1
jobs:
  build:
    docker:
      - image: tylerlum/ros_ompl_python_2:04.2020.V1
    steps:
      - run: mkdir -p /catkin_ws/src/local_pathfinding
      - run: source /opt/ros/melodic/setup.bash && cd /catkin_ws && catkin_make
      - checkout:
          path: /catkin_ws/src/local_pathfinding
      - run: source /opt/ros/melodic/setup.bash && cd /catkin_ws && catkin_make
      - run: source /opt/ros/melodic/setup.bash && source /catkin_ws/devel/setup.bash && cd /catkin_ws && catkin_make run_tests
